# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/cartridge.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'protobuf/cartridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protobuf/cartridge.proto\x12\x0bstratatools\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n\tCartridge\x12\x15\n\rserial_number\x18\x01 \x01(\x02\x12\x15\n\rmaterial_name\x18\x02 \x01(\t\x12\x19\n\x11manufacturing_lot\x18\x03 \x01(\t\x12\x36\n\x12manufacturing_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rlast_use_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x19initial_material_quantity\x18\x06 \x01(\x02\x12!\n\x19\x63urrent_material_quantity\x18\x07 \x01(\x02\x12\x14\n\x0ckey_fragment\x18\x08 \x01(\x0c\x12\x0f\n\x07version\x18\t \x01(\r\x12\x11\n\tsignature\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.cartridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTRIDGE']._serialized_start=75
  _globals['_CARTRIDGE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
